export interface Distillerie {
  slug: string;
  nom: string;
  ile: string;
  region: string;
  fondee: number;
  statut: string;
  acreage: string;
  production: string;
  photo: string;
  photoBandeau: string;
  couleur: string;
  description: string;
  histoire: string;
  specialites: string[];
  barriques: string[];
  recompenses: string[];
  futsDisponibles: number;
  coordonnees: { lat: number; lng: number };
  adresse: string;
  site?: string;
}

export const DISTILLERIES: Distillerie[] = [
  // ── GUADELOUPE ──────────────────────────────────────────────────────────────
  {
    slug: "damoiseau",
    nom: "Distillerie Damoiseau",
    ile: "Guadeloupe",
    region: "Le Moule, Grande-Terre",
    fondee: 1942,
    statut: "Famille Damoiseau — 3ème génération",
    acreage: "300 hectares de canne",
    production: "~3 000 HAP/an",
    photo: "/images/distilleries/damoiseau.jpg",
    photoBandeau: "/images/distilleries/damoiseau-bandeau.jpg",
    couleur: "#0F5240",
    description: "La plus grande distillerie de Guadeloupe, référence incontournable du rhum agricole AOC depuis 1942.",
    histoire: "Fondée en 1942 par Roger Damoiseau, la distillerie est aujourd'hui l'une des plus importantes de la Caraïbe. Implantée sur les terres de l'habitation Bellevue au Moule, elle cultive plus de 300 hectares de canne à sucre en Grande-Terre. Transmise de génération en génération, la famille Damoiseau a su préserver un savoir-faire artisanal tout en modernisant ses outils de production. Ses rhums blancs et vieux sont exportés dans plus de 40 pays et constituent une référence absolue pour les amateurs de rhum agricole AOC Guadeloupe.",
    specialites: [
      "Rhum Blanc AOC 50° et 55°",
      "Rhum Ambré 40°",
      "Rhum Vieux 3, 5, 8 et 12 ans",
      "Millésimes rares (1953, 1980, 1995)",
      "Rhum Blanc Cœur de Chauffe",
    ],
    barriques: [
      "Fûts de chêne américain (bourbon)",
      "Fûts de chêne français (Limousin)",
      "Fûts de 180L à 650L",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole Paris 2023",
      "Double Gold — San Francisco World Spirits Competition 2022",
      "Meilleur Rhum Agricole — RumFest Londres 2021",
    ],
    futsDisponibles: 3,
    coordonnees: { lat: 16.3275, lng: -61.3441 },
    adresse: "Habitation Bellevue, Le Moule, 97160 Guadeloupe",
    site: "https://www.damoiseau.fr",
  },
  {
    slug: "bologne",
    nom: "Distillerie Bologne",
    ile: "Guadeloupe",
    region: "Basse-Terre",
    fondee: 1887,
    statut: "Famille Marsolle — 4ème génération",
    acreage: "80 hectares de canne",
    production: "~800 HAP/an",
    photo: "/images/distilleries/bologne.jpg",
    photoBandeau: "/images/distilleries/bologne-bandeau.jpg",
    couleur: "#1A6B5A",
    description: "L'une des plus anciennes distilleries de Guadeloupe, nichée au pied du volcan de la Soufrière depuis 1887.",
    histoire: "Fondée en 1887, la distillerie Bologne est l'une des plus anciennes de Guadeloupe. Située au pied du volcan de la Soufrière, à Basse-Terre, elle bénéficie d'un terroir volcanique unique qui confère à ses rhums une minéralité et une complexité exceptionnelles. La famille Marsolle en est propriétaire depuis plusieurs générations et maintient une production artisanale de haute qualité. Les cannes sont cultivées sur des terres volcaniques riches, irriguées par les eaux pures descendant de la Soufrière.",
    specialites: [
      "Rhum Blanc AOC Bologne 50°",
      "Rhum Vieux Bologne 8 ans",
      "Cuvée 1887 — millésime prestige",
      "Rhum Blanc Bio certifié Agriculture Biologique",
    ],
    barriques: [
      "Fûts de chêne américain",
      "Fûts de chêne français",
      "Petits fûts 225L pour les cuvées prestige",
    ],
    recompenses: [
      "Médaille d'Argent — Concours Général Agricole 2023",
      "Coup de Cœur — Guide des Rhums 2022",
      "Bio certifié AB depuis 2018",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 16.0039, lng: -61.7089 },
    adresse: "Habitation Bologne, Basse-Terre, 97100 Guadeloupe",
  },
  {
    slug: "pere-labat",
    nom: "Distillerie Père Labat",
    ile: "Guadeloupe",
    region: "Marie-Galante",
    fondee: 1895,
    statut: "Coopérative de producteurs",
    acreage: "120 hectares de canne",
    production: "~600 HAP/an",
    photo: "/images/distilleries/pere-labat.jpg",
    photoBandeau: "/images/distilleries/pere-labat-bandeau.jpg",
    couleur: "#C8992A",
    description: "Trésor de Marie-Galante, l'île aux 100 moulins, Père Labat produit des rhums d'exception à haute teneur en alcool.",
    histoire: "Implantée sur l'île de Marie-Galante, surnommée 'l'île aux 100 moulins', la distillerie Père Labat perpétue depuis 1895 une tradition sucrière ancestrale. Marie-Galante est réputée pour la qualité exceptionnelle de sa canne à sucre, cultivée sur un sol calcaire unique. La distillerie produit des rhums à haute teneur en alcool (59° et plus), très appréciés des connaisseurs. Le nom rend hommage au père dominicain Jean-Baptiste Labat, pionnier de la distillation aux Antilles au XVIIe siècle.",
    specialites: [
      "Rhum Blanc 59° — signature Marie-Galante",
      "Rhum Blanc 67° — édition limitée",
      "Rhum Vieux 7 ans Fût de Chêne",
      "Cuvée Spéciale Père Labat XO",
    ],
    barriques: [
      "Fûts de chêne français 220L",
      "Fûts de chêne américain ex-bourbon",
      "Fûts de cognac Limousin pour les XO",
    ],
    recompenses: [
      "Trophée d'Or — Rhum Fest Paris 2023",
      "Médaille d'Or — International Rum Conference 2022",
      "Meilleur Rhum de Marie-Galante — Guide des Spiritueux 2023",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 15.9318, lng: -61.2700 },
    adresse: "Capesterre, Marie-Galante, 97140 Guadeloupe",
  },
  {
    slug: "bielle",
    nom: "Distillerie Bielle",
    ile: "Guadeloupe",
    region: "Marie-Galante",
    fondee: 1975,
    statut: "Famille Rameaux",
    acreage: "45 hectares de canne",
    production: "~350 HAP/an",
    photo: "/images/distilleries/bielle.jpg",
    photoBandeau: "/images/distilleries/bielle-bandeau.jpg",
    couleur: "#854F0B",
    description: "Distillerie familiale de Marie-Galante, Bielle est reconnue pour ses rhums vieux d'exception et son terroir calcaire unique.",
    histoire: "La distillerie Bielle, fondée en 1975 par la famille Rameaux, est l'une des plus emblématiques de Marie-Galante. Exploitant un terroir calcaire exceptionnel, elle produit des rhums agricoles AOC d'une grande finesse. Les cannes sont récoltées à la main sur les hauteurs de l'île, garantissant une qualité optimale du jus frais utilisé pour la distillation. Bielle est particulièrement reconnue pour ses vieux rhums, qui développent des arômes complexes de vanille, épices et fruits confits après plusieurs années en fût.",
    specialites: [
      "Rhum Blanc AOC Bielle 50°",
      "Rhum Vieux Bielle 5 ans",
      "Rhum Vieux Bielle 8 ans",
      "Grande Réserve — édition limitée millésimée",
    ],
    barriques: [
      "Fûts de chêne américain 180L",
      "Fûts de chêne français 225L",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Best Aged Rum Caribbean — Tales of the Cocktail 2021",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 15.9150, lng: -61.2580 },
    adresse: "Bielle, Grand-Bourg, Marie-Galante, 97112 Guadeloupe",
  },
  {
    slug: "longueteau",
    nom: "Distillerie Longueteau",
    ile: "Guadeloupe",
    region: "Capesterre-Belle-Eau, Basse-Terre",
    fondee: 1895,
    statut: "Famille Longueteau — 5ème génération",
    acreage: "200 hectares de canne",
    production: "~1 500 HAP/an",
    photo: "/images/distilleries/longueteau.jpg",
    photoBandeau: "/images/distilleries/longueteau-bandeau.jpg",
    couleur: "#0F6E56",
    description: "Nichée sur les flancs du volcan de la Soufrière, Longueteau cultive sa canne en agriculture biologique depuis 2012.",
    histoire: "La distillerie Longueteau est implantée à Capesterre-Belle-Eau, sur les terres fertiles de la Basse-Terre volcanique. Fondée en 1895, elle est l'une des rares distilleries guadeloupéennes à avoir converti l'intégralité de ses 200 hectares en agriculture biologique certifiée, depuis 2012. Les cannes poussent sur des sols volcaniques riches en minéraux, irriguées par les eaux pures des rivières descendant de la Soufrière. La famille Longueteau, à la cinquième génération, maintient un équilibre rare entre tradition et innovation.",
    specialites: [
      "Rhum Blanc Bio AOC 50° et 55°",
      "Rhum Genesis — emblème de la gamme",
      "Rhum Vieux 5 et 10 ans",
      "Cuvée Particulière — édition annuelle limitée",
    ],
    barriques: [
      "Fûts de chêne américain ex-bourbon",
      "Fûts de chêne français Allier",
      "Fûts de Porto et de Sauternes pour les cuvées spéciales",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Organic Rum — RumFest 2022",
      "Certification Agriculture Biologique depuis 2012",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 16.0453, lng: -61.5634 },
    adresse: "Capesterre-Belle-Eau, 97130 Guadeloupe",
  },
  {
    slug: "reimonenq",
    nom: "Distillerie Reimonenq",
    ile: "Guadeloupe",
    region: "Sainte-Rose, Basse-Terre",
    fondee: 1916,
    statut: "Groupe Bernard Hayot (GBH)",
    acreage: "150 hectares de canne",
    production: "~1 200 HAP/an",
    photo: "/images/distilleries/reimonenq.jpg",
    photoBandeau: "/images/distilleries/reimonenq-bandeau.jpg",
    couleur: "#3C3489",
    description: "Fondée en 1916 à Sainte-Rose, Reimonenq abrite le musée du rhum de Guadeloupe et produit des rhums de grande qualité.",
    histoire: "La distillerie Reimonenq, fondée en 1916 à Sainte-Rose sur la côte nord de Basse-Terre, est aujourd'hui propriété du Groupe Bernard Hayot (GBH). Elle est connue non seulement pour la qualité de ses rhums agricoles AOC, mais aussi pour abriter le célèbre Musée du Rhum de Guadeloupe, qui retrace l'histoire de la canne à sucre et du rhum dans l'archipel depuis le XVIIe siècle. Un lieu incontournable pour les amateurs et les touristes, associant patrimoine culturel et excellence du terroir.",
    specialites: [
      "Rhum Blanc AOC 50°",
      "Rhum Vieux Reimonenq 3 ans",
      "Rhum Vieux Reimonenq 6 ans",
      "Cuvée du Musée — édition patrimoniale",
    ],
    barriques: [
      "Fûts de chêne américain",
      "Fûts de chêne français",
    ],
    recompenses: [
      "Médaille d'Argent — Concours Général Agricole 2022",
      "Patrimoine culturel — Musée du Rhum labellisé",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 16.3242, lng: -61.6897 },
    adresse: "Sainte-Rose, 97115 Guadeloupe",
  },

  // ── MARTINIQUE ───────────────────────────────────────────────────────────────
  {
    slug: "clement",
    nom: "Habitation Clément",
    ile: "Martinique",
    region: "Le François",
    fondee: 1887,
    statut: "Groupe Bernard Hayot (GBH)",
    acreage: "250 hectares de canne",
    production: "~2 000 HAP/an",
    photo: "/images/distilleries/clement.jpg",
    photoBandeau: "/images/distilleries/clement-bandeau.jpg",
    couleur: "#0F5240",
    description: "L'une des plus prestigieuses habitations de Martinique, Clément conjugue excellence du rhum et patrimoine historique exceptionnel.",
    histoire: "L'Habitation Clément, fondée en 1887 par le Docteur Homère Clément, est l'une des plus prestigieuses de la Caraïbe. Son domaine historique classé, situé au François en Martinique, accueille chaque année des milliers de visiteurs venus admirer ses jardins tropicaux, sa galerie d'art et ses chais de vieillissement. Le rhum Clément est l'un des premiers à avoir été commercialisé sous le nom de 'rhum agricole', contribuant à définir cette catégorie d'excellence. Ses vieux rhums millésimés sont parmi les plus recherchés des collectionneurs du monde entier.",
    specialites: [
      "Rhum Blanc AOC Canne Bleue",
      "Rhum VSOP — vieilli minimum 4 ans",
      "XO — vieilli minimum 6 ans",
      "Millésimes rares (1952, 1970, 1976)",
      "Rhum Créole Shrubb — liqueur d'orange",
    ],
    barriques: [
      "Fûts de chêne américain ex-bourbon",
      "Fûts de chêne français Limousin",
      "Fûts de cognac pour les cuvées prestige",
      "Fûts de 180L à 650L",
    ],
    recompenses: [
      "Double Gold — San Francisco World Spirits 2023",
      "Meilleur Rhum Vieux Martinique — RumFest 2022",
      "Patrimoine historique classé — Domaine Clément",
      "Médaille d'Or — Concours Général Agricole 2023",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 14.6180, lng: -60.9240 },
    adresse: "Habitation Clément, Le François, 97240 Martinique",
    site: "https://www.rhum-clement.com",
  },
  {
    slug: "trois-rivieres",
    nom: "Distillerie Trois Rivières",
    ile: "Martinique",
    region: "Sainte-Luce",
    fondee: 1660,
    statut: "Groupe La Martiniquaise",
    acreage: "180 hectares de canne",
    production: "~1 800 HAP/an",
    photo: "/images/distilleries/trois-rivieres.jpg",
    photoBandeau: "/images/distilleries/trois-rivieres-bandeau.jpg",
    couleur: "#0891B2",
    description: "L'une des plus anciennes distilleries de la Caraïbe, fondée en 1660, Trois Rivières produit des rhums d'une complexité remarquable.",
    histoire: "Fondée en 1660, la distillerie Trois Rivières est l'une des plus anciennes de toute la Caraïbe. Implantée à Sainte-Luce, au sud de la Martinique, elle bénéficie d'un micro-climat exceptionnel et de terres volcaniques riches. Ses rhums sont réputés pour leur complexité aromatique unique, fruit d'un vieillissement soigné dans des caves naturellement tempérées. La distillerie a traversé les siècles en conservant ses méthodes traditionnelles tout en adoptant les meilleures pratiques modernes.",
    specialites: [
      "Rhum Blanc AOC 40° et 50°",
      "Rhum Ambré",
      "Rhum Vieux VSOP",
      "Cuvée de l'Océan — édition prestige",
      "Single Cask — embouteillages à la fût",
    ],
    barriques: [
      "Fûts de chêne américain 180L",
      "Fûts de chêne français 225L",
      "Fûts de Sauternes pour les cuvées spéciales",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Caribbean Rum — International Wine & Spirit 2022",
      "Trophée d'Excellence — Guide des Rhums 2023",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.4750, lng: -60.9180 },
    adresse: "Sainte-Luce, 97228 Martinique",
  },
  {
    slug: "hse",
    nom: "Habitation Saint-Étienne (HSE)",
    ile: "Martinique",
    region: "Le Gros-Morne",
    fondee: 1883,
    statut: "Groupe Maison Ferrand",
    acreage: "160 hectares de canne",
    production: "~1 200 HAP/an",
    photo: "/images/distilleries/hse.jpg",
    photoBandeau: "/images/distilleries/hse-bandeau.jpg",
    couleur: "#854F0B",
    description: "HSE est célèbre pour ses finitions en fûts de vins prestigieux — Sauternes, Bordeaux, Banyuls — qui donnent à ses rhums des arômes uniques.",
    histoire: "L'Habitation Saint-Étienne, fondée en 1883, est devenue une référence mondiale grâce à sa technique pionnière de finition en fûts de vins prestigieux. Rachetée par le Groupe Maison Ferrand en 2017, elle a bénéficié d'investissements considérables pour moderniser ses installations tout en préservant son patrimoine historique. HSE est particulièrement reconnue pour ses cuvées Black Sheriff et ses finitions en fûts de Sauternes, Banyuls et Cognac, qui lui valent une réputation internationale d'excellence.",
    specialites: [
      "Rhum Blanc AOC Canne Dorée",
      "Black Sheriff — emblème de la maison",
      "Finition Sauternes — 18 mois en fût de Sauternes",
      "Finition Banyuls",
      "Millésimes HSE — éditions limitées annuelles",
    ],
    barriques: [
      "Fûts de Sauternes (Château d'Yquem)",
      "Fûts de Banyuls",
      "Fûts de Cognac Limousin",
      "Fûts de chêne américain ex-bourbon",
    ],
    recompenses: [
      "Meilleur Rhum du Monde — Rum Experience 2023",
      "Double Gold — San Francisco World Spirits 2022",
      "Trophée Prestige — Guide des Spiritueux 2023",
      "Médaille d'Or Sauternes — Concours Général Agricole",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 14.6820, lng: -61.0210 },
    adresse: "Le Gros-Morne, 97213 Martinique",
    site: "https://www.hse-rum.com",
  },
  {
    slug: "saint-james",
    nom: "Distillerie Saint James",
    ile: "Martinique",
    region: "Sainte-Marie",
    fondee: 1765,
    statut: "Groupe La Martiniquaise",
    acreage: "300 hectares de canne",
    production: "~2 500 HAP/an",
    photo: "/images/distilleries/saint-james.jpg",
    photoBandeau: "/images/distilleries/saint-james-bandeau.jpg",
    couleur: "#1A2E4A",
    description: "Fondée en 1765, Saint James est l'une des plus anciennes marques de rhum au monde, pionnière de la bouteille carrée emblématique.",
    histoire: "Fondée en 1765 par le père Lefébure, la distillerie Saint James est l'une des plus anciennes marques de rhum au monde. Elle est célèbre pour avoir inventé la bouteille carrée emblématique qui facilita le transport par mer. Implantée à Sainte-Marie, au nord de la Martinique, elle dispose d'un musée du rhum et d'un espace de dégustation reconnu. Saint James est particulièrement appréciée pour ses rhums ambrés et vieux, qui constituent une initiation idéale au rhum agricole AOC Martinique.",
    specialites: [
      "Rhum Blanc AOC Fleur de Canne",
      "Rhum Paille — ambré léger",
      "Rhum Ambré",
      "Rhum Vieux VSOP et XO",
      "Cuvée 1765 — prestige anniversaire",
    ],
    barriques: [
      "Fûts de chêne américain",
      "Fûts de chêne français",
      "Fûts de 400L à 650L",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Meilleur Rhum Ambré — RumFest 2022",
      "Patrimoine historique — Musée Saint James labellisé",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 14.7760, lng: -61.0010 },
    adresse: "Sainte-Marie, 97230 Martinique",
    site: "https://www.saint-james.com",
  },
  {
    slug: "depaz",
    nom: "Distillerie Depaz",
    ile: "Martinique",
    region: "Saint-Pierre",
    fondee: 1917,
    statut: "Groupe La Martiniquaise",
    acreage: "100 hectares de canne",
    production: "~800 HAP/an",
    photo: "/images/distilleries/depaz.jpg",
    photoBandeau: "/images/distilleries/depaz-bandeau.jpg",
    couleur: "#7F77DD",
    description: "Construite sur les cendres du volcan de la Montagne Pelée, Depaz produit des rhums d'exception aux pieds du volcan depuis 1917.",
    histoire: "La distillerie Depaz occupe une place unique dans l'histoire de la Martinique. Construite en 1917 sur les ruines de l'ancienne habitation Depaz, détruite lors de l'éruption catastrophique de la Montagne Pelée en 1902, elle témoigne de la résilience du peuple martiniquais. Ses vignes de canne poussent sur des terres volcaniques exceptionnellement riches, à plus de 200 mètres d'altitude, au pied du volcan. Ces conditions uniques confèrent aux rhums Depaz une minéralité et une complexité aromatique incomparables.",
    specialites: [
      "Rhum Blanc AOC Grande Réserve 45°",
      "Rhum Vieux Depaz 6 ans",
      "Blue Cane — canne bleue exclusive",
      "XO Millesimé — éditions limitées",
      "Rhum Blanc Parcellaire",
    ],
    barriques: [
      "Fûts de chêne américain ex-bourbon",
      "Fûts de chêne français Tronçais",
      "Fûts de 180L à 400L",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Terroir Rum — International Rum Conference 2022",
      "Trophée Volcanique — Guide des Rhums 2023",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.7450, lng: -61.1760 },
    adresse: "Saint-Pierre, 97250 Martinique",
    site: "https://www.depaz.fr",
  },
  {
    slug: "jm",
    nom: "Distillerie J.M.",
    ile: "Martinique",
    region: "Macouba",
    fondee: 1845,
    statut: "Famille Dormoy",
    acreage: "120 hectares de canne",
    production: "~600 HAP/an",
    photo: "/images/distilleries/jm.jpg",
    photoBandeau: "/images/distilleries/jm-bandeau.jpg",
    couleur: "#C8992A",
    description: "Distillerie d'altitude nichée à Macouba, au nord de la Martinique, J.M. produit des rhums d'une rareté et d'une complexité absolues.",
    histoire: "La distillerie J.M., fondée en 1845, est nichée dans les hauteurs de Macouba, à la pointe nord de la Martinique, face à la Dominique. Son altitude, son micro-climat brumeux et ses terres volcaniques exceptionnelles lui permettent de produire des rhums d'une complexité et d'une rareté absolues. La production limitée — environ 600 HAP par an — en fait l'une des distilleries les plus confidentielles de la Caraïbe, dont les millésimes sont parmi les plus recherchés et valorisés au monde. Ses fûts de cognac Limousin donnent naissance à des rhums vieux d'exception.",
    specialites: [
      "Rhum Blanc AOC J.M. 50° et 55°",
      "Rhum Vieux J.M. VSOP",
      "J.M. XO — vieilli 6 ans minimum",
      "Millésimes rares (2001, 2005, 2009)",
      "Cuvée Spéciale Fût de Cognac",
    ],
    barriques: [
      "Fûts de cognac Limousin (spécialité maison)",
      "Fûts de chêne américain",
      "Petits fûts 180L pour les cuvées prestige",
    ],
    recompenses: [
      "Meilleur Rhum du Monde — Rum Experience 2022",
      "Triple Gold — San Francisco World Spirits 2023",
      "Distillerie de l'Année — International Rum Conference 2021",
      "Note parfaite 100/100 — Dave Broom Whisky Magazine 2022",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.8720, lng: -61.1050 },
    adresse: "Macouba, 97218 Martinique",
  },
  {
    slug: "la-mauny",
    nom: "Distillerie La Mauny",
    ile: "Martinique",
    region: "Rivière-Pilote",
    fondee: 1749,
    statut: "Groupe La Martiniquaise",
    acreage: "130 hectares de canne",
    production: "~1 000 HAP/an",
    photo: "/images/distilleries/la-mauny.jpg",
    photoBandeau: "/images/distilleries/la-mauny-bandeau.jpg",
    couleur: "#534AB7",
    description: "Fondée en 1749, La Mauny est l'une des plus anciennes distilleries de Martinique, nichée dans la verdoyante vallée de Rivière-Pilote.",
    histoire: "La distillerie La Mauny, fondée en 1749 sur l'habitation du même nom à Rivière-Pilote, au sud de la Martinique, est l'une des plus anciennes et des plus emblématiques de l'île. Son alambic pot still, l'un des rares encore en activité aux Antilles, confère à ses rhums une richesse aromatique unique.",
    specialites: [
      "Rhum Blanc AOC La Mauny 40° et 50°",
      "Rhum Ambré La Mauny",
      "Rhum Vieux VSOP",
      "Cuvée Prestige XO",
    ],
    barriques: [
      "Fûts de chêne américain ex-bourbon",
      "Fûts de chêne français",
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Best Martinique Rum — RumFest Londres 2021",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 14.4650, lng: -60.9350 },
    adresse: "Rivière-Pilote, 97211 Martinique",
  },

];

export function getDistillerie(slug: string): Distillerie | undefined {
  return DISTILLERIES.find(d => d.slug === slug);
}

export function getDistilleriesByIle(ile: string): Distillerie[] {
  return DISTILLERIES.filter(d => d.ile === ile);
}