// src/lib/distilleries.ts — Option B : champs multilingues {fr, en, es}
// Dans les composants : d.description[locale] ?? d.description.fr

export type LocaleStr = { fr: string; en: string; es: string };

export interface Distillerie {
  slug: string;
  nom: string;
  ile: string;
  region: string;
  fondee: number;
  statut: LocaleStr;
  acreage: string;
  production: string;
  photo: string;
  photoBandeau: string;
  couleur: string;
  description: LocaleStr;
  histoire: LocaleStr;
  specialites: LocaleStr[];
  barriques: LocaleStr[];
  recompenses: string[];
  futsDisponibles: number;
  coordonnees: { lat: number; lng: number };
  adresse: string;
  site?: string;
}

export const DISTILLERIES: Distillerie[] = [
  {
    slug: "damoiseau",
    nom: "Distillerie Damoiseau",
    ile: "Guadeloupe",
    region: "Le Moule, Grande-Terre",
    fondee: 1942,
    statut: {
      fr: "Famille Damoiseau — 3ème génération",
      en: "Damoiseau family — 3rd generation",
      es: "Familia Damoiseau — 3ª generación",
    },
    acreage: "300 hectares de canne",
    production: "~3 000 HAP/an",
    photo: "/images/distilleries/damoiseau.jpg",
    photoBandeau: "/images/distilleries/damoiseau-bandeau.jpg",
    couleur: "#0F5240",
    description: {
      fr: "La plus grande distillerie de Guadeloupe, référence incontournable du rhum agricole AOC depuis 1942.",
      en: "The largest distillery in Guadeloupe, an unmissable reference for AOC agricultural rum since 1942.",
      es: "La destilería más grande de Guadalupe, referencia indiscutible del ron agrícola AOC desde 1942.",
    },
    histoire: {
      fr: "Fondée en 1942 par Roger Damoiseau, la distillerie est aujourd'hui l'une des plus importantes de la Caraïbe. Implantée sur les terres de l'habitation Bellevue au Moule, elle cultive plus de 300 hectares de canne à sucre en Grande-Terre. Transmise de génération en génération, la famille Damoiseau a su préserver un savoir-faire artisanal tout en modernisant ses outils de production. Ses rhums blancs et vieux sont exportés dans plus de 40 pays.",
      en: "Founded in 1942 by Roger Damoiseau, the distillery is today one of the most important in the Caribbean. Located on the Bellevue estate in Le Moule, it cultivates over 300 hectares of sugarcane in Grande-Terre. Passed down through generations, the Damoiseau family has preserved artisanal know-how while modernizing production. Its white and aged rums are exported to over 40 countries.",
      es: "Fundada en 1942 por Roger Damoiseau, la destilería es hoy una de las más importantes del Caribe. Ubicada en la hacienda Bellevue en Le Moule, cultiva más de 300 hectáreas de caña de azúcar en Grande-Terre. Transmitida de generación en generación, la familia Damoiseau ha preservado el saber hacer artesanal modernizando la producción. Sus rones blancos y añejos se exportan a más de 40 países.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC 50° et 55°", en: "AOC White Rum 50° and 55°", es: "Ron Blanco AOC 50° y 55°" },
      { fr: "Rhum Ambré 40°", en: "Amber Rum 40°", es: "Ron Ámbar 40°" },
      { fr: "Rhum Vieux 3, 5, 8 et 12 ans", en: "Aged Rum 3, 5, 8 and 12 years", es: "Ron Añejo 3, 5, 8 y 12 años" },
      { fr: "Millésimes rares (1953, 1980, 1995)", en: "Rare vintages (1953, 1980, 1995)", es: "Añadas raras (1953, 1980, 1995)" },
      { fr: "Rhum Blanc Cœur de Chauffe", en: "White Rum Hearts Cut", es: "Ron Blanco Corazón de Destilación" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain (bourbon)", en: "American oak barrels (bourbon)", es: "Barriles de roble americano (bourbon)" },
      { fr: "Fûts de chêne français (Limousin)", en: "French oak barrels (Limousin)", es: "Barriles de roble francés (Limousin)" },
      { fr: "Fûts de 180L à 650L", en: "Barrels from 180L to 650L", es: "Barriles de 180L a 650L" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole Paris 2023",
      "Double Gold — San Francisco World Spirits Competition 2022",
      "Meilleur Rhum Agricole — RumFest Londres 2021",
    ],
    futsDisponibles: 3,
    coordonnees: { lat: 16.3275, lng: -61.3441 },
    adresse: "Habitation Bellevue, Le Moule, 97160 Guadeloupe",
    site: "https://www.damoiseau.fr",
  },
  {
    slug: "bologne",
    nom: "Distillerie Bologne",
    ile: "Guadeloupe",
    region: "Basse-Terre",
    fondee: 1887,
    statut: { fr: "Famille Marsolle — 4ème génération", en: "Marsolle family — 4th generation", es: "Familia Marsolle — 4ª generación" },
    acreage: "80 hectares de canne",
    production: "~800 HAP/an",
    photo: "/images/distilleries/bologne.jpg",
    photoBandeau: "/images/distilleries/bologne-bandeau.jpg",
    couleur: "#1A6B5A",
    description: {
      fr: "L'une des plus anciennes distilleries de Guadeloupe, nichée au pied du volcan de la Soufrière depuis 1887.",
      en: "One of the oldest distilleries in Guadeloupe, nestled at the foot of the Soufrière volcano since 1887.",
      es: "Una de las destilerías más antiguas de Guadalupe, ubicada al pie del volcán de la Soufrière desde 1887.",
    },
    histoire: {
      fr: "Fondée en 1887, la distillerie Bologne est l'une des plus anciennes de Guadeloupe. Située au pied du volcan de la Soufrière, elle bénéficie d'un terroir volcanique unique qui confère à ses rhums une minéralité et une complexité exceptionnelles. La famille Marsolle maintient une production artisanale de haute qualité.",
      en: "Founded in 1887, Bologne distillery is one of the oldest in Guadeloupe. Located at the foot of the Soufrière volcano, it benefits from a unique volcanic terroir that gives its rums exceptional minerality and complexity. The Marsolle family maintains high-quality artisanal production.",
      es: "Fundada en 1887, la destilería Bologne es una de las más antiguas de Guadalupe. Situada al pie del volcán de la Soufrière, se beneficia de un terroir volcánico único que confiere a sus rones una mineralidad y complejidad excepcionales.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Bologne 50°", en: "AOC White Rum Bologne 50°", es: "Ron Blanco AOC Bologne 50°" },
      { fr: "Rhum Vieux Bologne 8 ans", en: "Aged Rum Bologne 8 years", es: "Ron Añejo Bologne 8 años" },
      { fr: "Cuvée 1887 — millésime prestige", en: "Cuvée 1887 — prestige vintage", es: "Cuvée 1887 — añada de prestigio" },
      { fr: "Rhum Blanc Bio certifié Agriculture Biologique", en: "Organic White Rum — Organic Agriculture certified", es: "Ron Blanco Ecológico — certificado Agricultura Ecológica" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain", en: "American oak barrels", es: "Barriles de roble americano" },
      { fr: "Fûts de chêne français", en: "French oak barrels", es: "Barriles de roble francés" },
      { fr: "Petits fûts 225L pour les cuvées prestige", en: "Small 225L barrels for prestige cuvées", es: "Barriles pequeños 225L para las cuvées de prestigio" },
    ],
    recompenses: [
      "Médaille d'Argent — Concours Général Agricole 2023",
      "Coup de Cœur — Guide des Rhums 2022",
      "Bio certifié AB depuis 2018",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 16.0039, lng: -61.7089 },
    adresse: "Habitation Bologne, Basse-Terre, 97100 Guadeloupe",
  },
  {
    slug: "pere-labat",
    nom: "Distillerie Père Labat",
    ile: "Guadeloupe",
    region: "Marie-Galante",
    fondee: 1895,
    statut: { fr: "Coopérative de producteurs", en: "Producers' cooperative", es: "Cooperativa de productores" },
    acreage: "120 hectares de canne",
    production: "~600 HAP/an",
    photo: "/images/distilleries/pere-labat.jpg",
    photoBandeau: "/images/distilleries/pere-labat-bandeau.jpg",
    couleur: "#C8992A",
    description: {
      fr: "Trésor de Marie-Galante, l'île aux 100 moulins, Père Labat produit des rhums d'exception à haute teneur en alcool.",
      en: "Treasure of Marie-Galante, the island of 100 windmills, Père Labat produces exceptional high-proof rums.",
      es: "Tesoro de Marie-Galante, la isla de los 100 molinos, Père Labat produce rones de excepción con alta graduación alcohólica.",
    },
    histoire: {
      fr: "Implantée sur l'île de Marie-Galante, surnommée 'l'île aux 100 moulins', la distillerie Père Labat perpétue depuis 1895 une tradition sucrière ancestrale. Marie-Galante est réputée pour la qualité exceptionnelle de sa canne à sucre, cultivée sur un sol calcaire unique. Le nom rend hommage au père dominicain Jean-Baptiste Labat, pionnier de la distillation aux Antilles.",
      en: "Located on the island of Marie-Galante, nicknamed 'the island of 100 windmills', Père Labat distillery has perpetuated an ancestral sugar tradition since 1895. Marie-Galante is renowned for the exceptional quality of its sugarcane, grown on unique limestone soil. The name pays tribute to Dominican friar Jean-Baptiste Labat, pioneer of distillation in the Caribbean.",
      es: "Ubicada en la isla de Marie-Galante, apodada 'la isla de los 100 molinos', la destilería Père Labat perpetúa desde 1895 una tradición azucarera ancestral. El nombre rinde homenaje al fraile dominico Jean-Baptiste Labat, pionero de la destilación en el Caribe.",
    },
    specialites: [
      { fr: "Rhum Blanc 59° — signature Marie-Galante", en: "White Rum 59° — Marie-Galante signature", es: "Ron Blanco 59° — sello Marie-Galante" },
      { fr: "Rhum Blanc 67° — édition limitée", en: "White Rum 67° — limited edition", es: "Ron Blanco 67° — edición limitada" },
      { fr: "Rhum Vieux 7 ans Fût de Chêne", en: "Aged Rum 7 years Oak Barrel", es: "Ron Añejo 7 años Barrica de Roble" },
      { fr: "Cuvée Spéciale Père Labat XO", en: "Special Cuvée Père Labat XO", es: "Cuvée Especial Père Labat XO" },
    ],
    barriques: [
      { fr: "Fûts de chêne français 220L", en: "French oak barrels 220L", es: "Barriles de roble francés 220L" },
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
      { fr: "Fûts de cognac Limousin pour les XO", en: "Limousin cognac barrels for XO cuvées", es: "Barriles de coñac Limousin para los XO" },
    ],
    recompenses: [
      "Trophée d'Or — Rhum Fest Paris 2023",
      "Médaille d'Or — International Rum Conference 2022",
      "Meilleur Rhum de Marie-Galante — Guide des Spiritueux 2023",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 15.9318, lng: -61.2700 },
    adresse: "Capesterre, Marie-Galante, 97140 Guadeloupe",
  },
  {
    slug: "bielle",
    nom: "Distillerie Bielle",
    ile: "Guadeloupe",
    region: "Marie-Galante",
    fondee: 1975,
    statut: { fr: "Famille Rameaux", en: "Rameaux family", es: "Familia Rameaux" },
    acreage: "45 hectares de canne",
    production: "~350 HAP/an",
    photo: "/images/distilleries/bielle.jpg",
    photoBandeau: "/images/distilleries/bielle-bandeau.jpg",
    couleur: "#854F0B",
    description: {
      fr: "Distillerie familiale de Marie-Galante, Bielle est reconnue pour ses rhums vieux d'exception et son terroir calcaire unique.",
      en: "A family distillery from Marie-Galante, Bielle is renowned for its exceptional aged rums and unique limestone terroir.",
      es: "Destilería familiar de Marie-Galante, Bielle es reconocida por sus excepcionales rones añejos y su singular terroir calcáreo.",
    },
    histoire: {
      fr: "La distillerie Bielle, fondée en 1975 par la famille Rameaux, est l'une des plus emblématiques de Marie-Galante. Exploitant un terroir calcaire exceptionnel, elle produit des rhums agricoles AOC d'une grande finesse. Les cannes sont récoltées à la main sur les hauteurs de l'île.",
      en: "Bielle distillery, founded in 1975 by the Rameaux family, is one of the most emblematic in Marie-Galante. Exploiting an exceptional limestone terroir, it produces AOC agricultural rums of great finesse. The canes are harvested by hand on the heights of the island.",
      es: "La destilería Bielle, fundada en 1975 por la familia Rameaux, es una de las más emblemáticas de Marie-Galante. Explotando un excepcional terroir calcáreo, produce rones agrícolas AOC de gran finura. Las cañas se cosechan a mano en las alturas de la isla.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Bielle 50°", en: "AOC White Rum Bielle 50°", es: "Ron Blanco AOC Bielle 50°" },
      { fr: "Rhum Vieux Bielle 5 ans", en: "Aged Rum Bielle 5 years", es: "Ron Añejo Bielle 5 años" },
      { fr: "Rhum Vieux Bielle 8 ans", en: "Aged Rum Bielle 8 years", es: "Ron Añejo Bielle 8 años" },
      { fr: "Grande Réserve — édition limitée millésimée", en: "Grande Réserve — limited vintage edition", es: "Grande Réserve — edición limitada añada" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain 180L", en: "American oak barrels 180L", es: "Barriles de roble americano 180L" },
      { fr: "Fûts de chêne français 225L", en: "French oak barrels 225L", es: "Barriles de roble francés 225L" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Best Aged Rum Caribbean — Tales of the Cocktail 2021",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 15.9150, lng: -61.2580 },
    adresse: "Bielle, Grand-Bourg, Marie-Galante, 97112 Guadeloupe",
  },
  {
    slug: "longueteau",
    nom: "Distillerie Longueteau",
    ile: "Guadeloupe",
    region: "Capesterre-Belle-Eau, Basse-Terre",
    fondee: 1895,
    statut: { fr: "Famille Longueteau — 5ème génération", en: "Longueteau family — 5th generation", es: "Familia Longueteau — 5ª generación" },
    acreage: "200 hectares de canne",
    production: "~1 500 HAP/an",
    photo: "/images/distilleries/longueteau.jpg",
    photoBandeau: "/images/distilleries/longueteau-bandeau.jpg",
    couleur: "#0F6E56",
    description: {
      fr: "Nichée sur les flancs du volcan de la Soufrière, Longueteau cultive sa canne en agriculture biologique depuis 2012.",
      en: "Nestled on the slopes of the Soufrière volcano, Longueteau has cultivated its sugarcane organically since 2012.",
      es: "Enclavada en las laderas del volcán de la Soufrière, Longueteau cultiva su caña en agricultura ecológica desde 2012.",
    },
    histoire: {
      fr: "La distillerie Longueteau est implantée à Capesterre-Belle-Eau, sur les terres fertiles de la Basse-Terre volcanique. Fondée en 1895, elle est l'une des rares distilleries guadeloupéennes à avoir converti l'intégralité de ses 200 hectares en agriculture biologique certifiée depuis 2012.",
      en: "Longueteau distillery is located in Capesterre-Belle-Eau, on the fertile volcanic lands of Basse-Terre. Founded in 1895, it is one of the few Guadeloupean distilleries to have converted all 200 hectares to certified organic farming since 2012.",
      es: "La destilería Longueteau está ubicada en Capesterre-Belle-Eau, en las fértiles tierras volcánicas de Basse-Terre. Fundada en 1895, es una de las pocas destilerías guadalupeñas que ha convertido la totalidad de sus 200 hectáreas a agricultura ecológica certificada desde 2012.",
    },
    specialites: [
      { fr: "Rhum Blanc Bio AOC 50° et 55°", en: "Organic AOC White Rum 50° and 55°", es: "Ron Blanco Ecológico AOC 50° y 55°" },
      { fr: "Rhum Genesis — emblème de la gamme", en: "Rhum Genesis — flagship of the range", es: "Rhum Genesis — emblema de la gama" },
      { fr: "Rhum Vieux 5 et 10 ans", en: "Aged Rum 5 and 10 years", es: "Ron Añejo 5 y 10 años" },
      { fr: "Cuvée Particulière — édition annuelle limitée", en: "Cuvée Particulière — annual limited edition", es: "Cuvée Particulière — edición anual limitada" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
      { fr: "Fûts de chêne français Allier", en: "French Allier oak barrels", es: "Barriles de roble francés Allier" },
      { fr: "Fûts de Porto et de Sauternes pour les cuvées spéciales", en: "Port and Sauternes barrels for special cuvées", es: "Barriles de Oporto y Sauternes para las cuvées especiales" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Organic Rum — RumFest 2022",
      "Certification Agriculture Biologique depuis 2012",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 16.0453, lng: -61.5634 },
    adresse: "Capesterre-Belle-Eau, 97130 Guadeloupe",
  },
  {
    slug: "reimonenq",
    nom: "Distillerie Reimonenq",
    ile: "Guadeloupe",
    region: "Sainte-Rose, Basse-Terre",
    fondee: 1916,
    statut: { fr: "Groupe Bernard Hayot (GBH)", en: "Bernard Hayot Group (GBH)", es: "Grupo Bernard Hayot (GBH)" },
    acreage: "150 hectares de canne",
    production: "~1 200 HAP/an",
    photo: "/images/distilleries/reimonenq.jpg",
    photoBandeau: "/images/distilleries/reimonenq-bandeau.jpg",
    couleur: "#3C3489",
    description: {
      fr: "Fondée en 1916 à Sainte-Rose, Reimonenq abrite le musée du rhum de Guadeloupe et produit des rhums de grande qualité.",
      en: "Founded in 1916 in Sainte-Rose, Reimonenq is home to the Guadeloupe Rum Museum and produces high-quality rums.",
      es: "Fundada en 1916 en Sainte-Rose, Reimonenq alberga el Museo del Ron de Guadalupe y produce rones de gran calidad.",
    },
    histoire: {
      fr: "La distillerie Reimonenq, fondée en 1916 à Sainte-Rose, est connue pour abriter le célèbre Musée du Rhum de Guadeloupe, qui retrace l'histoire de la canne à sucre et du rhum dans l'archipel depuis le XVIIe siècle.",
      en: "Reimonenq distillery, founded in 1916 in Sainte-Rose, is known for housing the famous Guadeloupe Rum Museum, which traces the history of sugarcane and rum in the archipelago since the 17th century.",
      es: "La destilería Reimonenq, fundada en 1916 en Sainte-Rose, es conocida por albergar el famoso Museo del Ron de Guadalupe, que recorre la historia de la caña de azúcar y el ron en el archipiélago desde el siglo XVII.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC 50°", en: "AOC White Rum 50°", es: "Ron Blanco AOC 50°" },
      { fr: "Rhum Vieux Reimonenq 3 ans", en: "Aged Rum Reimonenq 3 years", es: "Ron Añejo Reimonenq 3 años" },
      { fr: "Rhum Vieux Reimonenq 6 ans", en: "Aged Rum Reimonenq 6 years", es: "Ron Añejo Reimonenq 6 años" },
      { fr: "Cuvée du Musée — édition patrimoniale", en: "Museum Cuvée — heritage edition", es: "Cuvée del Museo — edición patrimonial" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain", en: "American oak barrels", es: "Barriles de roble americano" },
      { fr: "Fûts de chêne français", en: "French oak barrels", es: "Barriles de roble francés" },
    ],
    recompenses: [
      "Médaille d'Argent — Concours Général Agricole 2022",
      "Patrimoine culturel — Musée du Rhum labellisé",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 16.3242, lng: -61.6897 },
    adresse: "Sainte-Rose, 97115 Guadeloupe",
  },
  {
    slug: "clement",
    nom: "Habitation Clément",
    ile: "Martinique",
    region: "Le François",
    fondee: 1887,
    statut: { fr: "Groupe Bernard Hayot (GBH)", en: "Bernard Hayot Group (GBH)", es: "Grupo Bernard Hayot (GBH)" },
    acreage: "250 hectares de canne",
    production: "~2 000 HAP/an",
    photo: "/images/distilleries/clement.jpg",
    photoBandeau: "/images/distilleries/clement-bandeau.jpg",
    couleur: "#0F5240",
    description: {
      fr: "L'une des plus prestigieuses habitations de Martinique, Clément conjugue excellence du rhum et patrimoine historique exceptionnel.",
      en: "One of the most prestigious estates in Martinique, Clément combines rum excellence with exceptional historical heritage.",
      es: "Una de las haciendas más prestigiosas de Martinica, Clément combina excelencia en ron con un excepcional patrimonio histórico.",
    },
    histoire: {
      fr: "L'Habitation Clément, fondée en 1887 par le Docteur Homère Clément, est l'une des plus prestigieuses de la Caraïbe. Son domaine historique classé, situé au François en Martinique, accueille chaque année des milliers de visiteurs. Le rhum Clément est l'un des premiers à avoir été commercialisé sous le nom de 'rhum agricole'.",
      en: "Habitation Clément, founded in 1887 by Doctor Homère Clément, is one of the most prestigious in the Caribbean. Its listed historic estate in Le François welcomes thousands of visitors every year. Clément rum was one of the first to be marketed as 'agricultural rum'.",
      es: "La Habitation Clément, fundada en 1887 por el Doctor Homère Clément, es una de las más prestigiosas del Caribe. Su histórica finca catalogada en Le François recibe miles de visitantes cada año. El ron Clément fue uno de los primeros en comercializarse como 'ron agrícola'.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Canne Bleue", en: "AOC White Rum Blue Cane", es: "Ron Blanco AOC Caña Azul" },
      { fr: "Rhum VSOP — vieilli minimum 4 ans", en: "VSOP Rum — aged minimum 4 years", es: "Ron VSOP — envejecido mínimo 4 años" },
      { fr: "XO — vieilli minimum 6 ans", en: "XO — aged minimum 6 years", es: "XO — envejecido mínimo 6 años" },
      { fr: "Millésimes rares (1952, 1970, 1976)", en: "Rare vintages (1952, 1970, 1976)", es: "Añadas raras (1952, 1970, 1976)" },
      { fr: "Rhum Créole Shrubb — liqueur d'orange", en: "Creole Shrubb Rum — orange liqueur", es: "Ron Créole Shrubb — licor de naranja" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
      { fr: "Fûts de chêne français Limousin", en: "French Limousin oak barrels", es: "Barriles de roble francés Limousin" },
      { fr: "Fûts de cognac pour les cuvées prestige", en: "Cognac barrels for prestige cuvées", es: "Barriles de coñac para las cuvées de prestigio" },
      { fr: "Fûts de 180L à 650L", en: "Barrels from 180L to 650L", es: "Barriles de 180L a 650L" },
    ],
    recompenses: [
      "Double Gold — San Francisco World Spirits 2023",
      "Meilleur Rhum Vieux Martinique — RumFest 2022",
      "Médaille d'Or — Concours Général Agricole 2023",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 14.6180, lng: -60.9240 },
    adresse: "Habitation Clément, Le François, 97240 Martinique",
    site: "https://www.rhum-clement.com",
  },
  {
    slug: "trois-rivieres",
    nom: "Distillerie Trois Rivières",
    ile: "Martinique",
    region: "Sainte-Luce",
    fondee: 1660,
    statut: { fr: "Groupe La Martiniquaise", en: "La Martiniquaise Group", es: "Grupo La Martiniquaise" },
    acreage: "180 hectares de canne",
    production: "~1 800 HAP/an",
    photo: "/images/distilleries/trois-rivieres.jpg",
    photoBandeau: "/images/distilleries/trois-rivieres-bandeau.jpg",
    couleur: "#0891B2",
    description: {
      fr: "L'une des plus anciennes distilleries de la Caraïbe, fondée en 1660, Trois Rivières produit des rhums d'une complexité remarquable.",
      en: "One of the oldest distilleries in the Caribbean, founded in 1660, Trois Rivières produces rums of remarkable complexity.",
      es: "Una de las destilerías más antiguas del Caribe, fundada en 1660, Trois Rivières produce rones de notable complejidad.",
    },
    histoire: {
      fr: "Fondée en 1660, la distillerie Trois Rivières est l'une des plus anciennes de toute la Caraïbe. Implantée à Sainte-Luce, au sud de la Martinique, elle bénéficie d'un micro-climat exceptionnel et de terres volcaniques riches. Ses rhums sont réputés pour leur complexité aromatique unique.",
      en: "Founded in 1660, Trois Rivières distillery is one of the oldest in the entire Caribbean. Located in Sainte-Luce, southern Martinique, it benefits from an exceptional microclimate and rich volcanic soils. Its rums are renowned for their unique aromatic complexity.",
      es: "Fundada en 1660, la destilería Trois Rivières es una de las más antiguas de todo el Caribe. Ubicada en Sainte-Luce, al sur de Martinica, se beneficia de un microclima excepcional y tierras volcánicas ricas. Sus rones son famosos por su singular complejidad aromática.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC 40° et 50°", en: "AOC White Rum 40° and 50°", es: "Ron Blanco AOC 40° y 50°" },
      { fr: "Rhum Ambré", en: "Amber Rum", es: "Ron Ámbar" },
      { fr: "Rhum Vieux VSOP", en: "VSOP Aged Rum", es: "Ron Añejo VSOP" },
      { fr: "Cuvée de l'Océan — édition prestige", en: "Cuvée de l'Océan — prestige edition", es: "Cuvée de l'Océan — edición de prestigio" },
      { fr: "Single Cask — embouteillages à la fût", en: "Single Cask — barrel bottlings", es: "Single Cask — embotellados de barrica" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain 180L", en: "American oak barrels 180L", es: "Barriles de roble americano 180L" },
      { fr: "Fûts de chêne français 225L", en: "French oak barrels 225L", es: "Barriles de roble francés 225L" },
      { fr: "Fûts de Sauternes pour les cuvées spéciales", en: "Sauternes barrels for special cuvées", es: "Barriles de Sauternes para las cuvées especiales" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Caribbean Rum — International Wine & Spirit 2022",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.4750, lng: -60.9180 },
    adresse: "Sainte-Luce, 97228 Martinique",
  },
  {
    slug: "hse",
    nom: "Habitation Saint-Étienne (HSE)",
    ile: "Martinique",
    region: "Le Gros-Morne",
    fondee: 1883,
    statut: { fr: "Groupe Maison Ferrand", en: "Maison Ferrand Group", es: "Grupo Maison Ferrand" },
    acreage: "160 hectares de canne",
    production: "~1 200 HAP/an",
    photo: "/images/distilleries/hse.jpg",
    photoBandeau: "/images/distilleries/hse-bandeau.jpg",
    couleur: "#854F0B",
    description: {
      fr: "HSE est célèbre pour ses finitions en fûts de vins prestigieux — Sauternes, Bordeaux, Banyuls — qui donnent à ses rhums des arômes uniques.",
      en: "HSE is famous for its finishing in prestigious wine barrels — Sauternes, Bordeaux, Banyuls — giving its rums unique aromas.",
      es: "HSE es famosa por sus acabados en barricas de vinos prestigiosos — Sauternes, Burdeos, Banyuls — que confieren a sus rones aromas únicos.",
    },
    histoire: {
      fr: "L'Habitation Saint-Étienne, fondée en 1883, est devenue une référence mondiale grâce à sa technique pionnière de finition en fûts de vins prestigieux. Rachetée par le Groupe Maison Ferrand en 2017, elle est particulièrement reconnue pour ses cuvées Black Sheriff et ses finitions en fûts de Sauternes, Banyuls et Cognac.",
      en: "Habitation Saint-Étienne, founded in 1883, became a world reference thanks to its pioneering technique of finishing in prestigious wine barrels. Acquired by the Maison Ferrand Group in 2017, it is particularly recognized for its Black Sheriff cuvées and Sauternes, Banyuls and Cognac barrel finishes.",
      es: "La Habitation Saint-Étienne, fundada en 1883, se convirtió en referencia mundial gracias a su técnica pionera de acabado en barricas de vinos prestigiosos. Adquirida por el Grupo Maison Ferrand en 2017, destaca por sus cuvées Black Sheriff y sus acabados en barricas de Sauternes, Banyuls y Coñac.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Canne Dorée", en: "AOC White Rum Golden Cane", es: "Ron Blanco AOC Caña Dorada" },
      { fr: "Black Sheriff — emblème de la maison", en: "Black Sheriff — house flagship", es: "Black Sheriff — emblema de la casa" },
      { fr: "Finition Sauternes — 18 mois en fût de Sauternes", en: "Sauternes Finish — 18 months in Sauternes barrel", es: "Acabado Sauternes — 18 meses en barrica de Sauternes" },
      { fr: "Finition Banyuls", en: "Banyuls Finish", es: "Acabado Banyuls" },
      { fr: "Millésimes HSE — éditions limitées annuelles", en: "HSE Vintages — annual limited editions", es: "Añadas HSE — ediciones limitadas anuales" },
    ],
    barriques: [
      { fr: "Fûts de Sauternes (Château d'Yquem)", en: "Sauternes barrels (Château d'Yquem)", es: "Barricas de Sauternes (Château d'Yquem)" },
      { fr: "Fûts de Banyuls", en: "Banyuls barrels", es: "Barricas de Banyuls" },
      { fr: "Fûts de Cognac Limousin", en: "Limousin Cognac barrels", es: "Barricas de Coñac Limousin" },
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
    ],
    recompenses: [
      "Meilleur Rhum du Monde — Rum Experience 2023",
      "Double Gold — San Francisco World Spirits 2022",
    ],
    futsDisponibles: 2,
    coordonnees: { lat: 14.6820, lng: -61.0210 },
    adresse: "Le Gros-Morne, 97213 Martinique",
    site: "https://www.hse-rum.com",
  },
  {
    slug: "saint-james",
    nom: "Distillerie Saint James",
    ile: "Martinique",
    region: "Sainte-Marie",
    fondee: 1765,
    statut: { fr: "Groupe La Martiniquaise", en: "La Martiniquaise Group", es: "Grupo La Martiniquaise" },
    acreage: "300 hectares de canne",
    production: "~2 500 HAP/an",
    photo: "/images/distilleries/saint-james.jpg",
    photoBandeau: "/images/distilleries/saint-james-bandeau.jpg",
    couleur: "#1A2E4A",
    description: {
      fr: "Fondée en 1765, Saint James est l'une des plus anciennes marques de rhum au monde, pionnière de la bouteille carrée emblématique.",
      en: "Founded in 1765, Saint James is one of the oldest rum brands in the world, pioneer of the iconic square bottle.",
      es: "Fundada en 1765, Saint James es una de las marcas de ron más antiguas del mundo, pionera en la icónica botella cuadrada.",
    },
    histoire: {
      fr: "Fondée en 1765 par le père Lefébure, la distillerie Saint James est l'une des plus anciennes marques de rhum au monde. Elle est célèbre pour avoir inventé la bouteille carrée emblématique qui facilita le transport par mer.",
      en: "Founded in 1765 by Father Lefébure, Saint James distillery is one of the oldest rum brands in the world. It is famous for inventing the iconic square bottle that facilitated sea transport.",
      es: "Fundada en 1765 por el padre Lefébure, la destilería Saint James es una de las marcas de ron más antiguas del mundo. Es famosa por haber inventado la icónica botella cuadrada que facilitó el transporte marítimo.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Fleur de Canne", en: "AOC White Rum Fleur de Canne", es: "Ron Blanco AOC Fleur de Canne" },
      { fr: "Rhum Paille — ambré léger", en: "Paille Rum — light amber", es: "Ron Paille — ámbar ligero" },
      { fr: "Rhum Ambré", en: "Amber Rum", es: "Ron Ámbar" },
      { fr: "Rhum Vieux VSOP et XO", en: "VSOP and XO Aged Rum", es: "Ron Añejo VSOP y XO" },
      { fr: "Cuvée 1765 — prestige anniversaire", en: "Cuvée 1765 — anniversary prestige", es: "Cuvée 1765 — aniversario de prestigio" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain", en: "American oak barrels", es: "Barriles de roble americano" },
      { fr: "Fûts de chêne français", en: "French oak barrels", es: "Barriles de roble francés" },
      { fr: "Fûts de 400L à 650L", en: "Barrels from 400L to 650L", es: "Barriles de 400L a 650L" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Meilleur Rhum Ambré — RumFest 2022",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 14.7760, lng: -61.0010 },
    adresse: "Sainte-Marie, 97230 Martinique",
    site: "https://www.saint-james.com",
  },
  {
    slug: "depaz",
    nom: "Distillerie Depaz",
    ile: "Martinique",
    region: "Saint-Pierre",
    fondee: 1917,
    statut: { fr: "Groupe La Martiniquaise", en: "La Martiniquaise Group", es: "Grupo La Martiniquaise" },
    acreage: "100 hectares de canne",
    production: "~800 HAP/an",
    photo: "/images/distilleries/depaz.jpg",
    photoBandeau: "/images/distilleries/depaz-bandeau.jpg",
    couleur: "#7F77DD",
    description: {
      fr: "Construite sur les cendres du volcan de la Montagne Pelée, Depaz produit des rhums d'exception aux pieds du volcan depuis 1917.",
      en: "Built on the ashes of the Montagne Pelée volcano, Depaz has produced exceptional rums at the foot of the volcano since 1917.",
      es: "Construida sobre las cenizas del volcán de la Montaña Pelée, Depaz produce rones de excepción al pie del volcán desde 1917.",
    },
    histoire: {
      fr: "La distillerie Depaz occupe une place unique dans l'histoire de la Martinique. Construite en 1917 sur les ruines de l'ancienne habitation Depaz, détruite lors de l'éruption catastrophique de la Montagne Pelée en 1902, elle témoigne de la résilience du peuple martiniquais.",
      en: "Depaz distillery holds a unique place in Martinique's history. Built in 1917 on the ruins of the former Depaz estate, destroyed during the catastrophic eruption of Montagne Pelée in 1902, it bears witness to the resilience of the Martinican people.",
      es: "La destilería Depaz ocupa un lugar único en la historia de Martinica. Construida en 1917 sobre las ruinas de la antigua hacienda Depaz, destruida durante la catastrófica erupción de la Montaña Pelée en 1902, atestigua la resiliencia del pueblo martinicano.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC Grande Réserve 45°", en: "AOC White Rum Grande Réserve 45°", es: "Ron Blanco AOC Grande Réserve 45°" },
      { fr: "Rhum Vieux Depaz 6 ans", en: "Aged Rum Depaz 6 years", es: "Ron Añejo Depaz 6 años" },
      { fr: "Blue Cane — canne bleue exclusive", en: "Blue Cane — exclusive blue sugarcane", es: "Blue Cane — caña azul exclusiva" },
      { fr: "XO Millesimé — éditions limitées", en: "XO Millesimé — limited editions", es: "XO Millesimé — ediciones limitadas" },
      { fr: "Rhum Blanc Parcellaire", en: "Single Plot White Rum", es: "Ron Blanco de Parcela" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
      { fr: "Fûts de chêne français Tronçais", en: "French Tronçais oak barrels", es: "Barriles de roble francés Tronçais" },
      { fr: "Fûts de 180L à 400L", en: "Barrels from 180L to 400L", es: "Barriles de 180L a 400L" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2023",
      "Best Terroir Rum — International Rum Conference 2022",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.7450, lng: -61.1760 },
    adresse: "Saint-Pierre, 97250 Martinique",
    site: "https://www.depaz.fr",
  },
  {
    slug: "jm",
    nom: "Distillerie J.M.",
    ile: "Martinique",
    region: "Macouba",
    fondee: 1845,
    statut: { fr: "Famille Dormoy", en: "Dormoy family", es: "Familia Dormoy" },
    acreage: "120 hectares de canne",
    production: "~600 HAP/an",
    photo: "/images/distilleries/jm.jpg",
    photoBandeau: "/images/distilleries/jm-bandeau.jpg",
    couleur: "#C8992A",
    description: {
      fr: "Distillerie d'altitude nichée à Macouba, au nord de la Martinique, J.M. produit des rhums d'une rareté et d'une complexité absolues.",
      en: "A high-altitude distillery nestled in Macouba, northern Martinique, J.M. produces rums of absolute rarity and complexity.",
      es: "Destilería de altitud enclavada en Macouba, al norte de Martinica, J.M. produce rones de absoluta rareza y complejidad.",
    },
    histoire: {
      fr: "La distillerie J.M., fondée en 1845, est nichée dans les hauteurs de Macouba, à la pointe nord de la Martinique. Son altitude, son micro-climat brumeux et ses terres volcaniques exceptionnelles lui permettent de produire des rhums d'une complexité et d'une rareté absolues.",
      en: "J.M. distillery, founded in 1845, is nestled in the heights of Macouba, at the northern tip of Martinique. Its altitude, misty microclimate and exceptional volcanic soils allow it to produce rums of absolute complexity and rarity.",
      es: "La destilería J.M., fundada en 1845, está enclavada en las alturas de Macouba, en la punta norte de Martinica. Su altitud, microclima neblinoso y excepcionales tierras volcánicas le permiten producir rones de absoluta complejidad y rareza.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC J.M. 50° et 55°", en: "AOC White Rum J.M. 50° and 55°", es: "Ron Blanco AOC J.M. 50° y 55°" },
      { fr: "Rhum Vieux J.M. VSOP", en: "J.M. VSOP Aged Rum", es: "Ron Añejo J.M. VSOP" },
      { fr: "J.M. XO — vieilli 6 ans minimum", en: "J.M. XO — aged minimum 6 years", es: "J.M. XO — envejecido mínimo 6 años" },
      { fr: "Millésimes rares (2001, 2005, 2009)", en: "Rare vintages (2001, 2005, 2009)", es: "Añadas raras (2001, 2005, 2009)" },
      { fr: "Cuvée Spéciale Fût de Cognac", en: "Special Cuvée Cognac Barrel", es: "Cuvée Especial Barrica de Coñac" },
    ],
    barriques: [
      { fr: "Fûts de cognac Limousin (spécialité maison)", en: "Limousin cognac barrels (house specialty)", es: "Barricas de coñac Limousin (especialidad de la casa)" },
      { fr: "Fûts de chêne américain", en: "American oak barrels", es: "Barriles de roble americano" },
      { fr: "Petits fûts 180L pour les cuvées prestige", en: "Small 180L barrels for prestige cuvées", es: "Barriles pequeños 180L para las cuvées de prestigio" },
    ],
    recompenses: [
      "Meilleur Rhum du Monde — Rum Experience 2022",
      "Triple Gold — San Francisco World Spirits 2023",
      "Distillerie de l'Année — International Rum Conference 2021",
    ],
    futsDisponibles: 1,
    coordonnees: { lat: 14.8720, lng: -61.1050 },
    adresse: "Macouba, 97218 Martinique",
  },
  {
    slug: "la-mauny",
    nom: "Distillerie La Mauny",
    ile: "Martinique",
    region: "Rivière-Pilote",
    fondee: 1749,
    statut: { fr: "Groupe La Martiniquaise", en: "La Martiniquaise Group", es: "Grupo La Martiniquaise" },
    acreage: "130 hectares de canne",
    production: "~1 000 HAP/an",
    photo: "/images/distilleries/la-mauny.jpg",
    photoBandeau: "/images/distilleries/la-mauny-bandeau.jpg",
    couleur: "#534AB7",
    description: {
      fr: "Fondée en 1749, La Mauny est l'une des plus anciennes distilleries de Martinique, nichée dans la verdoyante vallée de Rivière-Pilote.",
      en: "Founded in 1749, La Mauny is one of the oldest distilleries in Martinique, nestled in the lush valley of Rivière-Pilote.",
      es: "Fundada en 1749, La Mauny es una de las destilerías más antiguas de Martinica, enclavada en el exuberante valle de Rivière-Pilote.",
    },
    histoire: {
      fr: "La distillerie La Mauny, fondée en 1749 sur l'habitation du même nom à Rivière-Pilote, au sud de la Martinique, est l'une des plus anciennes et des plus emblématiques de l'île. Son alambic pot still, l'un des rares encore en activité aux Antilles, confère à ses rhums une richesse aromatique unique.",
      en: "La Mauny distillery, founded in 1749 on the estate of the same name in Rivière-Pilote, southern Martinique, is one of the oldest and most emblematic on the island. Its pot still, one of the few still in operation in the Caribbean, gives its rums a unique aromatic richness.",
      es: "La destilería La Mauny, fundada en 1749 en la hacienda del mismo nombre en Rivière-Pilote, al sur de Martinica, es una de las más antiguas y emblemáticas de la isla. Su alambique pot still, uno de los pocos aún en funcionamiento en el Caribe, confiere a sus rones una riqueza aromática única.",
    },
    specialites: [
      { fr: "Rhum Blanc AOC La Mauny 40° et 50°", en: "AOC White Rum La Mauny 40° and 50°", es: "Ron Blanco AOC La Mauny 40° y 50°" },
      { fr: "Rhum Ambré La Mauny", en: "Amber Rum La Mauny", es: "Ron Ámbar La Mauny" },
      { fr: "Rhum Vieux VSOP", en: "VSOP Aged Rum", es: "Ron Añejo VSOP" },
      { fr: "Cuvée Prestige XO", en: "Prestige Cuvée XO", es: "Cuvée Prestige XO" },
    ],
    barriques: [
      { fr: "Fûts de chêne américain ex-bourbon", en: "Ex-bourbon American oak barrels", es: "Barriles de roble americano ex-bourbon" },
      { fr: "Fûts de chêne français", en: "French oak barrels", es: "Barriles de roble francés" },
    ],
    recompenses: [
      "Médaille d'Or — Concours Général Agricole 2022",
      "Best Martinique Rum — RumFest Londres 2021",
    ],
    futsDisponibles: 0,
    coordonnees: { lat: 14.4650, lng: -60.9350 },
    adresse: "Rivière-Pilote, 97211 Martinique",
  },
];

export function getDistillerie(slug: string): Distillerie | undefined {
  return DISTILLERIES.find(d => d.slug === slug);
}

export function getDistilleriesByIle(ile: string): Distillerie[] {
  return DISTILLERIES.filter(d => d.ile === ile);
}